// <auto-generated />
using System;
using FCEService.Infrastructure.Persistance.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FCEService.Migrations
{
    [DbContext(typeof(FCE_DBContext))]
    [Migration("20260707031536_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FCEService.Domain.Aggregates.CalculatedMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BMR")
                        .HasColumnType("float")
                        .HasColumnName("BMR");

                    b.Property<string>("BMRStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("BMRStatus");

                    b.Property<double>("CalorieTarget")
                        .HasColumnType("float")
                        .HasColumnName("CalorieTarget");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("TDEE")
                        .HasColumnType("float")
                        .HasColumnName("TDEE");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CalculatedMetrics", (string)null);
                });

            modelBuilder.Entity("FCEService.Domain.Aggregates.UserFitnessStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkoutDays")
                        .HasColumnType("int");

                    b.Property<string>("activity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("goal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("UserFitnessStats", (string)null);
                });

            modelBuilder.Entity("FCEService.Domain.Entities.UserAssignedPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NutritionPlan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkoutPlan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("calorieIntake")
                        .HasColumnType("float");

                    b.Property<string>("goal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("userId");

                    b.ToTable("UserAssignedPlans", (string)null);
                });

            modelBuilder.Entity("FCEService.Domain.Entities.UserPlanHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExternalPlanId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ResonForChange")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserPlanHistory", (string)null);
                });

            modelBuilder.Entity("FCEService.Domain.Aggregates.CalculatedMetrics", b =>
                {
                    b.OwnsOne("FCEService.Domain.ValueObject.BMRRange", "BMRRange", b1 =>
                        {
                            b1.Property<int>("CalculatedMetricsId")
                                .HasColumnType("int");

                            b1.Property<double>("Max")
                                .HasColumnType("float")
                                .HasColumnName("BMRRangeMax");

                            b1.Property<double>("Min")
                                .HasColumnType("float")
                                .HasColumnName("BMRRangeMin");

                            b1.HasKey("CalculatedMetricsId");

                            b1.ToTable("CalculatedMetrics");

                            b1.WithOwner()
                                .HasForeignKey("CalculatedMetricsId");
                        });

                    b.Navigation("BMRRange")
                        .IsRequired();
                });

            modelBuilder.Entity("FCEService.Domain.Aggregates.UserFitnessStats", b =>
                {
                    b.OwnsOne("FCEService.Domain.ValueObject.PhysicalStats", "physicalStats", b1 =>
                        {
                            b1.Property<int>("UserFitnessStatsId")
                                .HasColumnType("int");

                            b1.Property<int>("Age")
                                .HasColumnType("int")
                                .HasColumnName("Age");

                            b1.Property<string>("Gender")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("Gender");

                            b1.Property<double>("Height")
                                .HasColumnType("float")
                                .HasColumnName("Height");

                            b1.Property<double>("Weight")
                                .HasColumnType("float")
                                .HasColumnName("Weight");

                            b1.HasKey("UserFitnessStatsId");

                            b1.ToTable("UserFitnessStats");

                            b1.WithOwner()
                                .HasForeignKey("UserFitnessStatsId");
                        });

                    b.Navigation("physicalStats")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
