services:

  # =========================================================
  # AUTHENTICATION SERVICE
  # =========================================================
  authenticationservice:
    image: fitnessapp.authenticationservice
    build:
      context: .
      dockerfile: AuthenticationService/Dockerfile
    container_name: authentication-service
    ports:
      - "8087:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080

      ConnectionStrings__AuthenticationConnection: "Server=host.docker.internal,1433;Database=AuthenticationService;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;Encrypt=False"

      RabbitMQConnection__HostName: host.docker.internal
      RabbitMQConnection__Port: 5673
      RabbitMQConnection__UserName: guest
      RabbitMQConnection__Password: guest

    restart: on-failure

  # =========================================================
  # USER PROFILE SERVICE
  # =========================================================
  userprofileservice:
    image: fitnessapp.userprofileservice
    build:
      context: .
      dockerfile: UserProfileService/Dockerfile
    container_name: userprofile-service
    ports:
      - "8088:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080

      ConnectionStrings__UserProfileConnection: "Server=host.docker.internal,1433;Database=UserProfileService;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;Encrypt=False"

    restart: on-failure

  # =========================================================
  # WORKOUT SERVICE
  # =========================================================
  workoutservice:
    image: fitnessapp.workoutservice
    build:
      context: .
      dockerfile: FitnessApp/Dockerfile
    container_name: workout-service
    ports:
      - "8089:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080

      ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=WorkoutService;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;Encrypt=False"

      RabbitMqOptions__HostName: host.docker.internal
      RabbitMqOptions__Port: 5673
      RabbitMqOptions__UserName: guest
      RabbitMqOptions__Password: guest
      RabbitMqOptions__ExchangeName: workout.events

    restart: on-failure

  # =========================================================
  # PROGRESS TRACKING SERVICE
  # =========================================================
  progresstrackingservice:
    image: fitnessapp.progresstrackingservice
    build:
      context: .
      dockerfile: ProgressTrackingService/Dockerfile
    container_name: progress-tracking-service
    ports:
      - "8090:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080

      ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=ProgressTrackingService;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;Encrypt=False"

      ConnectionStrings__RedisConnectionLocal: "host.docker.internal:6379"

      RabbitMQConnection__HostName: host.docker.internal
      RabbitMQConnection__Port: 5673
      RabbitMQConnection__UserName: guest
      RabbitMQConnection__Password: guest

    restart: on-failure

  # =========================================================
  # NOTIFICATION SERVICE
  # =========================================================
  notificationservice:
    image: fitnessapp.notificationservice
    build:
      context: .
      dockerfile: NotificationService/Dockerfile
    container_name: notification-service
    ports:
      - "8085:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080

      ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=NotificationService;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;Encrypt=False"

      RabbitMQ__HostName: host.docker.internal
      RabbitMQ__Port: 5673
      RabbitMQ__UserName: guest
      RabbitMQ__Password: guest
      RabbitMQ__ExchangeName: progress.events
      RabbitMQ__QueueName: notification.achievement-earned
      RabbitMQ__RoutingKey: achievement_earned

    restart: on-failure

  # =========================================================
  # FCE SERVICE
  # =========================================================
  fceservice:
    image: fitnessapp.fceservice
    build:
      context: .
      dockerfile: FCEService/Dockerfile
    container_name: fce-service
    ports:
      - "8086:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080

      ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=FCEService;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;Encrypt=False"

    restart: on-failure

  # =========================================================
  # API GATEWAY
  # =========================================================
  api_gateway:
    image: api_gateway

    build:
      context: .
      dockerfile: API_Gateway/Dockerfile

    container_name: api-gateway

    ports:
      - "9090:8080"

    depends_on:
      - authenticationservice
      - userprofileservice
      - workoutservice
      - progresstrackingservice
      - notificationservice
      - fceservice

    restart: on-failure